import type { MiddlewareHandler } from "astro";
// cloudflare:workers is an external resolved at runtime by the Workers runtime.
// @ts-ignore — types generated by `npm run generate-types` after first deploy
import { env } from "cloudflare:workers";

// @keystatic/astro@5 reads Astro.locals.runtime.env, removed in Astro v6.
// Replace runtime with a plain object so Keystatic finds its env bindings.
export const onRequest: MiddlewareHandler = (context, next) => {
  (context.locals as any).runtime = { env };
  return next();
};
